### ISSUE TITLE
Cannot load Web UI

### ISSUE THREAD

**Issue by Steven-Harris** [jshridha/docker-nzbgetvpn#18]
Not sure what is going on I have completed all the required information and even set the PGID and PUID environment variables.

Here are the logs
[output.txt](https://github.com/jshridha/docker-nzbgetvpn/files/4400511/output.txt)

**Comment by Steven-Harris** [comment]
Also I am using the docker template from unraid

**Comment by Steven-Harris** [comment]
I had to set PGID and PUID to 0 (root)

**Comment by jshridha** [comment]
You should be able to go back to your old PGID and PUID if you manually set the permissions to the nzbget directory. It looks like nzbget isn't starting because it can't write to the directory:

```
2020-03-29 21:37:09,685 DEBG 'nzbget-script' stderr output:\
/usr/bin/nzbget_bin/nzbget.log: Permission denied\
/usr/bin/nzbget_bin/nzbget.log: Permission denied\
/usr/bin/nzbget_bin/nzbget.log: Permission denied\
/usr/bin/nzbget_bin/nzbget.log: Permission denied\
```

A simple `chown -Rv 99:100 /mnt/user/appdata/nzbget` modified for your directory and PUID/PGID should fix the problem.
