### ISSUE TITLE
Set python2 as default - for NZBGet Extension scripts

### ISSUE THREAD

**Issue by nstead** [jshridha/docker-nzbgetvpn#8]
Most of the Extension scripts available for NZBGet require python2, but the docker container has python3 as the default.

I have to remember, every time I update the image, to go and change the symlink /usr/bin/python to point to python2.

(I know, I could edit the shebang in the scripts, but there are a lot of them!)

I appreciate that some people may also be using python3 scripts - would it be possible to include an Environment variable to select the default python interpreter?

**Comment by jshridha** [comment]
Python2 is losing support in 2020. The migration will have to happen eventually so I'd suggest editing those shebangs! Otherwise you can always add "ln -sf /usr/sbin/python3 /usr/sbin/python" to your startup command.

I'm hesitant to change the default due to unexpected downstream issues. Arch has python3 as the default python and I don't know what changing what will mess with.
