### ISSUE TITLE
Switch to binhex/arch-openvpn:latest

### ISSUE THREAD

**Issue by nemchik** [jshridha/docker-nzbgetvpn#9]
I think it would be beneficial for this image to use `binhex/arch-openvpn:latest` rather than `binhex/arch-openvpn:2018040901` as all other binhex containers released that use the `binhex/arch-openvpn` base image use the `latest` tag (as far as I can tell).

**Comment by jshridha** [comment]
I use a specific tag to make sure that future changes to binhex's base image don't break my builds. This is important because sometimes he adds/removes features that can break my build scripts. This hasn't happened for a while, but I prefer to be explicit in my dependencies.

That said, I'll certainly consider the change to help keep image sizes down.
